version: "3.7"

services:
  sqhg_fastapi:
    container_name: sqhg_fastapi
    restart: unless-stopped
    volumes:
      - ./sqhg:/usr/src/app
    env_file:
      - ./envs/mysql.env
    depends_on:
      - sqhg_db

  sqhg_db:
    image: mysql:8.0.33
    container_name: sqhg_db
    restart: unless-stopped
    command: mysqld
    ports:
      - 3306:3306
    env_file:
      - envs/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
