version: "3.7"

services:
  postgres:
    networks:
      - sqhg


  sqhg_fastapi:
    build:
      context: ./backend
      args:
        MODE: ci
    environment:
      MODE: ci
      LOGS_ROOT: /var/log/backend
    command: ["./docker/ci.sh"]
    ports:
      - "8000:8000"
    env_file:
      - ./envs/postgres.env
    depends_on:
      - sqhg_db
    networks:
      - sqhg
