version: "3.7"

services:
  sqhg_fastapi:
    build:
      context: ./backend
      args:
        MODE: development
    environment:
      MODE: development
      PORT: 8000
      HOST: 0.0.0.0
      LOGS_ROOT: /var/log/backend
    command: sh -c "sh ./docker/start.sh"
    ports:
      - "8000:8000"
    env_file:
      - ./envs/postgres.env
    depends_on:
      - sqhg_db
    networks:
      - sqhg

  sqhg_db:
    networks:
      - sqhg

volumes:
  postgres_data:

networks:
  sqhg:
