version: "3.7"

services:
  sqhg_fastapi:
    container_name: sqhg_fastapi
    restart: unless-stopped
    volumes:
      - ./sqhg:/usr/src/app
    env_file:
      - ./envs/postgres.env
    depends_on:
      - sqhg_db

  sqhg_db:
    image: postgres:14
    container_name: sqhg_db
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - envs/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
