version: "3.7"

services:
  sqhg_fastapi:
    build:
      context: ./sqhg
      args:
        MODE: production
    environment:
      MODE: production
      PORT: 8000
      HOST: 0.0.0.0
      LOGS_ROOT: /var/log/sqhg
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
    command: bash ./docker/start.sh
    ports:
      - "8000:8000"
    env_file:
      - ./envs/postgres.env
    networks:
      - sqhg

  sqhg_db:
    networks:
      - sqhg

networks:
  sqhg:
