version: "3.7"

services:
  sqhg_fastapi:
    build:
      context: ./sqhg
      args:
        MODE: ci
    environment:
      MODE: ci
      LOGS_ROOT: /var/log/sqhg
    command: bash ./docker/ci.sh
    ports:
      - "8000:8000"
    env_file:
      - ./envs/postgres.env
    networks:
      - sqhg

  sqhg_db:
    networks:
      - sqhg

networks:
  sqhg:
