version: "3.7"

services:
  sqhg_fastapi:
    build:
      context: ./sqhg
      args:
        MODE: production
    environment:
      MODE: production
      PORT: 8000
      HOST: 0.0.0.0
      LOGS_ROOT: /var/log/sqhg
      WAIT_HOSTS: sqhg_db:5432
    command: sh -c "sh ./docker/start.sh"
    ports:
      - "8000:8000"
    env_file:
      - ./envs/postgres.env
    networks:
      - sqhg

  sqhg_db:
    networks:
      - sqhg

networks:
  sqhg:
