version: "3.7"

services:
  sqhg_fastapi:
    build:
      context: ./sqhg
      args:
        MODE: production
    environment:
      MODE: production
      PORT: 8000
      HOST: 0.0.0.0
      LOGS_ROOT: /var/log/sqhg
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_MAIL_FROM: ${SMTP_MAIL_FROM}
      SUPERUSER_USERNAME: ${SUPERUSER_USERNAME}
      SUPERUSER_EMAIL: ${SUPERUSER_EMAIL}
      SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
    command: bash ./docker/start.sh
    ports:
      - "8000:8000"
    env_file:
      - ./envs/postgres.env
    networks:
      - sqhg

  sqhg_db:
    networks:
      - sqhg

networks:
  sqhg:
