version: "3.7"

services:
  sqhg_fastapi:
    build:
      context: ./sqhg
      args:
        MODE: development
    environment:
      MODE: development
      PORT: 8000
      HOST: 0.0.0.0
      LOGS_ROOT: /var/log/sqhg
      WAIT_HOSTS: sqhg_db:5432
      SECRET_KEY: 8d7ba1016828942be9bc7887c08cd7637586d73d4cfc3b41c51d51b5328c54ad
      ALGORITHM: HS256
    command: sh -c "sh ./docker/start.sh"
    ports:
      - "8000:8000"
    env_file:
      - ./envs/postgres.env
    depends_on:
      - sqhg_db
    networks:
      - sqhg

  sqhg_db:
    networks:
      - sqhg

volumes:
  postgres_data:

networks:
  sqhg:
