[tool.ruff]
line-length = 119
exclude = [
    'alembic/versions'
]
select = ['ARG', 'C4', 'C90', 'E', 'F', 'N', 'PIE', 'PL', 'RET', 'S', 'SIM', 'SLF', 'T20', 'W']

[tool.ruff.per-file-ignores]
'tests/*.py' = ['S101', 'ARG001']

[tool.ruff.pylint]
max-args = 5

[tool.ruff.mccabe]
max-complexity = 12

[tool.pytest.ini_options]
filterwarnings = [
    'ignore::DeprecationWarning',
]
