"""001

Revision ID: de4d78cb075d
Revises: bda7e54a051b
Create Date: 2023-06-12 15:24:11.764145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de4d78cb075d'
down_revision = 'bda7e54a051b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('area', 'status')
    op.add_column('superior', sa.Column('subordinates', sa.Integer(), nullable=False))
    op.add_column('survey', sa.Column('status', sa.Enum('scheduled', 'active', 'done', name='surveystatus'), nullable=False))
    op.add_column('token', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('token', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('token', 'is_active')
    op.drop_column('survey', 'status')
    op.drop_column('superior', 'subordinates')
    op.add_column('area', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('area', 'is_active')
    # ### end Alembic commands ###
