"""001

Revision ID: 3f42249552af
Revises: bda7e54a051b
Create Date: 2023-06-30 20:18:55.250463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f42249552af'
down_revision = 'bda7e54a051b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_answer_survey_id', table_name='answer')
    op.drop_constraint('answer_survey_id_fkey', 'answer', type_='foreignkey')
    op.drop_column('answer', 'survey_id')
    op.add_column('area', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('area', 'status')
    op.add_column('question', sa.Column('survey_id', sa.Integer(), nullable=False))
    op.drop_index('ix_question_survey_model_id', table_name='question')
    op.create_index(op.f('ix_question_survey_id'), 'question', ['survey_id'], unique=False)
    op.drop_constraint('question_survey_model_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'survey', ['survey_id'], ['id'])
    op.drop_column('question', 'survey_model_id')
    op.add_column('superior', sa.Column('subordinates', sa.Integer(), nullable=False))
    op.add_column('survey', sa.Column('status', sa.Enum('scheduled', 'active', 'done', name='surveystatus'), nullable=False))
    op.add_column('survey_model', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.add_column('token', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('token', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('token', 'is_active')
    op.drop_column('survey_model', 'is_archived')
    op.drop_column('survey', 'status')
    op.drop_column('superior', 'subordinates')
    op.add_column('question', sa.Column('survey_model_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_survey_model_id_fkey', 'question', 'survey_model', ['survey_model_id'], ['id'])
    op.drop_index(op.f('ix_question_survey_id'), table_name='question')
    op.create_index('ix_question_survey_model_id', 'question', ['survey_model_id'], unique=False)
    op.drop_column('question', 'survey_id')
    op.add_column('area', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('area', 'is_active')
    op.add_column('answer', sa.Column('survey_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('answer_survey_id_fkey', 'answer', 'survey', ['survey_id'], ['id'])
    op.create_index('ix_answer_survey_id', 'answer', ['survey_id'], unique=False)
    # ### end Alembic commands ###
