"""001

Revision ID: cc9eb866a588
Revises: bda7e54a051b
Create Date: 2023-05-29 16:26:51.884072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9eb866a588'
down_revision = 'bda7e54a051b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unit_id', table_name='unit')
    op.drop_table('unit')
    op.add_column('area', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('area', 'status')
    op.add_column('superior', sa.Column('subordinates', sa.Integer(), nullable=False))
    op.add_column('survey', sa.Column('status', sa.Enum('scheduled', 'active', 'done', name='surveystatus'), nullable=False))
    op.add_column('token', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('token', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('token', 'is_active')
    op.drop_column('survey', 'status')
    op.drop_column('superior', 'subordinates')
    op.add_column('area', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('area', 'is_active')
    op.create_table('unit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('register_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('deactivation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='unit_pkey')
    )
    op.create_index('ix_unit_id', 'unit', ['id'], unique=False)
    # ### end Alembic commands ###
